version: "3.8"

services:
  astro:
    build: .
    ports:
      - "4321:4321"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
    command: npm run dev -- --host